name: Merge Android Kernel with Latest Stable Linux

on:
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if current directory is a Git repository
        run: |
          if [ -d .git ]; then
            echo "Current directory is a Git repository"
          else
            echo "Current directory is not a Git repository"
            git init
          fi

      - name: Check current kernel version
        run: |
          git fetch --update-shallow
          echo "Current kernel version: $(git describe --tags)"

      - name: Check latest stable Linux version
        run: |
          latest_stable_version=$(wget https://kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/refs/tags -qO - | grep -oE 'v[0-9]+.[0-9]+.[0-9]+')

  merge-kernel:
    needs: check-versions
    runs-on: ubuntu-latest
    steps:
      - name: Check if latest stable Linux version is newer
        run: |
          latest_stable_version=$(wget https://kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/refs/tags -qO - | grep -oE 'v[0-9]+.[0-9]+.[0-9]+')
          current_version=$(git describe --tags)
          if [[ $latest_stable_version > $current_version ]]; then
            echo "Latest stable Linux version is newer"
          else
            echo "Latest stable Linux version is not newer"
            exit 1
          fi

      - name: Merge latest stable Linux with current kernel
        run: |
          git fetch linux-stable
          git merge linux-stable/v${latest_stable_version}

      - name: Create new branch for merged kernel
        run: |
          git checkout -b merged-kernel

      - name: Save information about the merge process
        run: |
          echo "Merged kernel version: $(git describe --tags)" > merge_info.txt
          echo "Latest stable Linux version: $latest_stable_version" >> merge_info.txt

      - name: Upload merge info
        uses: actions/upload-artifact@v2
        with:
          name: merge_info
          path: merge_info.txt
