name: Update Kernel Source

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily at midnight
  workflow_dispatch:  # Manually dispatch trigger
    inputs:
      run-manual:
        description: 'Run the workflow manually'
        default: 'false'
        required: false

jobs:
  update_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "donvito007"
          git config --global user.email "frditc@gmail.com"

      - name: Get current version of Android kernel source
        run: |
          CURRENT_VERSION=$(git describe --abbrev=0 --tags)

      - name: Get latest version of stable Linux
        run: |
          LATEST_LINUX_VERSION=$(curl -LsSf https://www.kernel.org/releases.json | jq -r '.latest_stable.version')

      - name: Compare versions
        run: |
          IS_NEWER=false
          if [ "$CURRENT_VERSION" != "$LATEST_LINUX_VERSION" ]; then
            IS_NEWER=true
          fi

      - name: Merge with the latest stable Linux
        if: $IS_NEWER == true || github.event.inputs.run-manual == 'true'
        run: |
          git checkout -b updated_kernel
          git pull --rebase origin main
          git remote add linux-stable https://github.com/torvalds/linux.git
          git fetch linux-stable
          git merge linux-stable/"$LATEST_LINUX_VERSION"

      - name: Save information to a text file
        run: |
          echo "Current version: $CURRENT_VERSION" > update_log.txt
          echo "Latest stable Linux version: $LATEST_LINUX_VERSION" >> update_log.txt
          echo "Is newer: $IS_NEWER" >> update_log.txt

      - name: Upload log file
        if: $IS_NEWER == true || github.event.inputs.run-manual == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: update_log
          path: update_log.txt
