name: Update Kernel Source

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily at midnight
  workflow_dispatch:  # Manually dispatch trigger
    inputs:
      run-manual:
        description: 'Run the workflow manually'
        default: 'true'
        required: false

jobs:
  update_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "donvito07"
          git config --global user.email "frditc@gmail.com"

      - name: Fetch tags from the remote repository
        run: git fetch --tags

      - name: Get current branch name
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV

      - name: Get latest version of stable Linux tag
        run: |
          LATEST_LINUX_TAG=$(curl -LsSf https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          echo "LATEST_LINUX_TAG=$LATEST_LINUX_TAG" >> $GITHUB_ENV

      - name: Get commit hash for latest stable Linux tag
        run: |
          LATEST_LINUX_COMMIT=$(git rev-list -n 1 "$LATEST_LINUX_TAG")
          echo "LATEST_LINUX_COMMIT=$LATEST_LINUX_COMMIT" >> $GITHUB_ENV

      - name: Compare versions and set IS_NEWER flag
        run: |
          if [ "$CURRENT_BRANCH" != "$LATEST_LINUX_TAG" ]; then
            echo "IS_NEWER=true" >> $GITHUB_ENV
          else
            echo "IS_NEWER=false" >> $GITHUB_ENV
          fi

      - name: Merge with the latest stable Linux
        if: env.IS_NEWER == 'true' || github.event.inputs.run-manual == 'true'
        run: |
          git checkout -b updated_kernel "$LATEST_LINUX_COMMIT"
          git pull --rebase origin main
          git merge "$CURRENT_BRANCH"

      - name: Save information to a text file
        run: |
          echo "Current branch: $CURRENT_BRANCH" > update_log.txt
          echo "Latest stable Linux tag: $LATEST_LINUX_TAG" >> update_log.txt
          echo "Is newer: $IS_NEWER" >> update_log.txt

      - name: Upload log file
        if: env.IS_NEWER == 'true' || github.event.inputs.run-manual == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: update_log
          path: update_log.txt
