name: Merge with upstream

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch upstream
        run: git fetch upstream

      - name: Check out latest tag
        run: git checkout upstream/v4.19.288

      - name: Merge changes
        run: git merge upstream/v4.19.288

      - name: Push changes
        run: git push
